### ISSUE TITLE
Magic number in superlorentzian function?

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRILab#25]
Hey Jean-François,

Could you explain how this "magic" number was chosen in the superlorentzian calculation?

https://github.com/neuropoly/qMTLab/blob/master/Common/lineshape/superlorentzianLineshape.m#L17

I understand that the purpose of the 0.00016 factor is to conserve continuity at exactly 1500 Hz,  but why/how was the delta of 1140 Hz chosen for lowest possible value the on-res case? Won't this bias/underestimate the Sf table calculations for the protocol point values <1500 Hz, of which we've always used in our own protocols (see Levesque optimization paper, 2011, and Sled's 2001 paper)? 

Cheers,

Mathieu

**Comment by jfcabana** [comment]
Hi Mathieu,

The extrapolation of the SuperLorentzian lineshape near resonance was made to handle the infinite value at G(0) for this lineshape for the on resonance methods (SIR-FSE and bSSFP). 

The values used in the extrapolation were chosen empirically to reproduce the extrapolation made in the Gloor 2008 paper (Fig.8). They used a fixed value on resonance of G(0) = 1.4 x 10^-5 s^-1 for some T2r value I don't recall. To get to this value in a continuous, smooth way, I used a quadratic extrapolation of the lineshape towards G(0) for delta < 1500 Hz. 

From my understanding, the exact absorption lineshape of the restricted pool is unclear near resonance. If you want to avoid bias for the SPGR method, the 'onres' argument in the function can be set to false, then no extrapolation is made. This option is not implemented in the GUI though, but you could make the change in the [computeWB ](https://github.com/neuropoly/qMTLab/blob/master/SPGR/functions/computeWB.m) function by changing line 4 to onres = 0; but that would affect on resonance methods as well. Maybe a better way would be to set the 'onres' variable to 1 in the [SPGR_fit](https://github.com/neuropoly/qMTLab/blob/master/SPGR/functions/SPGR_fit.m) function and pass it to computeWB where it is called. You would also need to do the same in the three analytical expressions files (SPGR_(Scw/Srp/Y)_fun.m).

I do suggest you compare results using both options, as I never really took the time to do it myself. Let me know what you find! Let me know if you think it would be best to set the default for SPGR to not use extrapolation, I could make the change.

Cheers,
JF

**Comment by mathieuboudreau** [comment]
Thanks JF!

I think our legacy code dealt with this region a little bit differently, https://github.com/mathieuboudreau/qMTLab_MNI_Legacy/blob/master/superlrtz_line.m#L38,  but I don't fully understand what/why they were doing here either.

I'll move along with what I'm intending on doing, and if I can't reproduce some of Ives old results, I'll dig into this a bit more.

Cheers,

Mathieu
