### ISSUE TITLE
Do not delete this repo please.

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/qMRILab#27]
Hi all,

I see that a private qMRILab repo has been created in neuropoly, and all the files of a branch of this repo have been copied into that one. That is not a great way to share between repos, as the entire commit history of this repo is no longer contained in qMRILab. I'm not quite sure why this is being done, as it is not the correct way to track commits between two repositories. 

The correct method would be to make qMTLab a submodule of qMRI lab. If you were not aware of this feature, please read up on it here: https://git-scm.com/book/en/v2/Git-Tools-Submodules

Ideally, qMTLab and qDLab (and whichever else q_Labs) would be kept separate repositories, and would be added as submodules into qMRILab, where a common GUI could be created and handled...

**Comment by tanguyduval** [comment]
Hi Mathieu, thanks for your feedback! 

A submodule seems to be the way to go (didn't know about this)! I'll look at that on monday,

Best,
Tanguy

**Comment by mathieuboudreau** [comment]
Great! It's one of the hidden features of git that makes it extremely useful!

From what it looks like to me, you want to extend qMTLab to qMRILab, but keep a repo named "qMTLab" so that people reading the paper can still go to the link that's indicated in the paper.  

What I actually think might be ideal to do is:

1- Rename the current qMTLab repo to qMRILab (https://help.github.com/articles/renaming-a-repository/) 

2- Create a new empty repository named qMTLab (since you will be able to do so once you've renamed the old one to qMRILab).

3- In the new empty qMTLab repo, create a short readme saying that qMTLab has been extended to qMRILab, and show a link to the qMRILab repo.

4- In qMTLab, add a submodule so that it contains the current latest commit the qMRILab repo (which still only contains the qMTLab stuff). https://gist.github.com/gitaarik/8735255 (this link also have info on how to change the commit point of submodules: http://stackoverflow.com/questions/10914022/how-to-check-out-specific-version-of-a-submodule-using-git-submodule). This way, people will know what was the last supported "qMTLab" commit prior to your merge.

5- Finally, In qMRILab, merge the the branch that has the extended qMRILab code so that it's up to date.

This way, the (new) qMTLab repo will have a submodule containing the old qMTLab code (but pointing a specific commit in the qMRILab repo), and you can keep working on qMRILab with all the commits saved and tracked in the "qMRILab" repo (also the branches still exist!).

Let me know if this all makes sense or not, and if you have any questions! I find it's worth it to create an empty test repository to try out new git/github features, like submodules, before trying them on your main repos (though changes are always reversible, unless you delete a repo).

Cheers,

Mathieu

**Comment by tanguyduval** [comment]
Ok, it's done..
IMPORTANT!! Your local repo is now linked to the new qMTLab (empty with only the submodule)..
So you need to clone the new qMRILab and work from this repo. don't push anything to qMTLab.

**Comment by mathieuboudreau** [comment]
Great, thank you very much Tanguy!!
