### ISSUE TITLE
bug with repmat on R2013a

### ISSUE THREAD

**Issue by HarrisNami** [neuropoly/qMRILab#33]
L162 to 166 should be modify as follows
````
    FitDataPanelObj = findobj('Tag', 'FitDataFileBrowserPanel');
    for ii=1:MethodCount
        FileBrowserList(ii) = MethodBrowser(FitDataPanelObj);
    end
    SetAppData(FileBrowserList);

````

**Comment by tanguyduval** [comment]
already solved in branch "simulation"

**Comment by jcohenadad** [comment]
I would suggest to close an issue once the branch has been merged on master (to avoid unseen solved issue in the future).

**Comment by tanguyduval** [comment]
ok done. I just mistakenly push to master... but apparently current master was buggy and I solved quite a few of them. Harry and Darya are testing the new master now.
